# Generated by Django 5.0.6 on 2024-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='joinCode',
            field=models.CharField(blank=True, db_column='joinCode', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
