# Generated by Django 5.0.6 on 2024-09-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='rules',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
