# Generated by Django 5.0.6 on 2024-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
