# Generated by Django 5.0.7 on 2024-10-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0002_alter_events_description_alter_events_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='eventid',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='segmentid',
        ),
    ]
