# Generated by Django 5.0.6 on 2024-09-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0002_alter_photos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='icon',
            field=models.ForeignKey(blank=True, db_column='photo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventful.photos'),
        ),
    ]
