# Generated by Django 5.0.6 on 2024-10-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0002_alter_segments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
