# Generated by Django 5.0.6 on 2024-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0003_alter_segments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
