# Generated by Django 5.0.6 on 2024-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventful', '0004_alter_users_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isactive',
            field=models.CharField(blank=True, db_column='isActive', default='False', null=True),
        ),
    ]
