POST http://localhost:8000/api/login/
Content-Type: application/json

{"username" : "remo12", "password" : "Remo123@"}

###

POST http://localhost:8000/api/register/
Content-Type: application/json

{"username" : "remo12",  "password" : "Remo123@", "name" : "Remigiusz", "surname" : "Grzemo",
"email" : "Woj@gmail.com","registrationdate" : "2001-11-11",
 "birthdate" : "2001-03-11", "language" : "pl"}

###

GET http://localhost:8000/api/user/
Content-Type: application/json

{"username" : "s"}

###

GET http://localhost:8000/api/checkUsername/
Content-Type: application/json

{"username" : "asdf"}

###

POST http://localhost:8000/api/logout/
Content-Type: application/json

{"token" : "VJIDXESI4RUD1Y4ObeSb"}

###

POST http://localhost:8000/api/logoutUsername/
Content-Type: application/json

{"username" : "Fox2137"}

###
POST http://localhost:8000/api/create_event/
Content-Type: application/json

{"name" : "Template Event", "description" : "Description"}

###