POST http://localhost:8000/api/login/
Content-Type: application/json

{"username" : "remo", "password" : "123"}

###

POST http://localhost:8000/api/register/
Content-Type: application/json

{"username" : "remo",  "password" : "123", "name" : "Remigiusz", "surname" : "Grzemo",
"email" : "Woj@gmail.com","registrationdate" : "2001-11-11",
 "birthdate" : "2001-03-11", "language" : "pl"}

###

GET http://localhost:8000/api/user/
Content-Type: application/json

{"username" : "remo"}

###

POST http://localhost:8000/api/logout/
Content-Type: application/json

{"token" : "XsCznrvDu6ynmDvjbh1n"}

###